# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_auto_20170418_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='jobseeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.Jobseeker'),
        ),
    ]
