# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_auto_20170418_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='jobseeker_id',
            field=models.CharField(default=88759849, max_length=8, primary_key=True, serialize=False),
        ),
    ]
