# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_auto_20170418_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='jobseeker_id',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='JobseekerId',
            field=models.CharField(default=68640657, max_length=8, primary_key=True, serialize=False),
        ),
    ]
